print("hello")
print("hello this is a \"so-called\" program where we can use this escape sequence character to show quotes")
print("Separator works like this",3,2,1,"we can add any character","its a positional argument do not add anything after it",sep='<<<>>>')
print("All these print stmts start on a new line",end='<NewPrint>')
print("to avoid that, use the end arg on previous print stmt")